name: HTML

on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
        path: main
    - name: Build HTML for main
      run: |
           #wget -O widoco.jar https://github.com/dgarijo/Widoco/releases/download/v1.4.17/java-11-widoco-1.4.17-jar-with-dependencies.jar
           wget -O widoco.jar https://github.com/dgarijo/Widoco/releases/download/v1.4.25/widoco-1.4.25-jar-with-dependencies_JDK-11.jar
           mkdir public 
           java -jar widoco.jar -ontFile main/lp.ttl -outFolder public -htaccess -uniteSections -includeAnnotationProperties -lang de-en  -getOntologyMetadata -noPlaceHolderText -rewriteAll -webVowl
           ls public/doc
           cp public/doc/index-de.html public/doc/index.html
           
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: public/doc
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
