name: Reasoning
on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
    - name: Reasoning
      run: |
           curl -L -o robot.jar "https://github.com/ontodev/robot/releases/latest/download/robot.jar"
           java -jar robot.jar reason --reasoner hermit --input lehrplan.ttl --output reasoned.ttl
           rm robot.jar
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_NAME: 'main' #optional defaults to master
